version: "3.2"

services:
  backend:  
    image: open-reg-backend
    container_name: open-reg-backend-staging
    build: .
    ports:
      - ${PORT}:${PORT}
    environment: 
      PORT: 
      NODE_ENV: staging