version: "3.2"

services:
  backend: 
    image: open-reg-backend
    container_name: open-reg-backend
    environment:
      MONGO_URL:
      SECRET:
      NODE_ENV:
      CHULA_APP_ID:
      CHULA_APP_SECRET:
