version: "3.2"

services:
  traefik:
    image: 'traefik:v2.0.0'
    container_name: 'traefik'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'

      - 'traefik.http.routers.api.entrypoints=websecure'
      - 'traefik.http.routers.api.rule=Host(`traefik.openreg.app`)'
      - 'traefik.http.routers.api.tls.certresolver=myhttpchallenge'
      - 'traefik.http.routers.api.service=api@internal'
    command:
      # - '--log.level=DEBUG'
      # - '--api.insecure=true'
      - '--api=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true'
      - '--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web'
      # - '--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
      - '--certificatesresolvers.myhttpchallenge.acme.email=ichannel.jakpat@gmail.com'
      - '--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  backend:
    container_name: open-reg-backend-prod
    build: .
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`api.openreg.app`)'
      - 'traefik.http.routers.backend.entrypoints=websecure'
      - 'traefik.http.routers.backend.tls.certresolver=myhttpchallenge'
      - 'traefik.http.services.backend.loadbalancer.server.port=3000'
