version: "3.2"

services:
  backend: 
    image: node:8
    container_name: open-reg-backend-dev
    depends_on:
      - db
    restart: always
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
    ports:
      - 3000:3000
    environment: 
      MONGO_URL: mongodb://db/open-reg
      SECRET: secret
      NODE_ENV: development
    working_dir: /app
    command: ['yarn', 'start:dev']

  db:
    image: mongo:4.2
    container_name: open-reg-db
    restart: always
    volumes: 
      - ./volumes/mongodb:/data/db
      - ./volumes/mongodb_config:/data/configdb
    ports:
      - 27017:27017